name: athkar_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+8

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  hijri: ^3.0.0
  adhan: ^2.0.0
  intl: any

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons:

  card_swiper: ^3.0.1
  percent_indicator: ^4.2.2
  provider: ^6.0.5
  vibration:
  shared_preferences: ^2.1.2

  flutter_local_notifications: ^20.1.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.0
  geolocator: ^12.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0F0F0F"
  image: image/logo.png
  image_dark: image/logodark.png

  android_12:
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#0F0F0F"
    image: image/logo.png
    image_dark: image/logodark.png


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: image/icon.png


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/font/Amiri-Regular.ttf

    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf

    - family: Baloo
      fonts:
        - asset: assets/font/BalooBhaijaan2-VariableFont_wght.ttf
